version: '3.8'
services:
  app:
    image: "poshjosh/aidebate:${APP_VERSION:-latest}"
    stdin_open: true # equivalent to docker run -i
    tty: true        # equivalent to docker run -t
    build:
      context: src/aidebate
      dockerfile: ../../Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime
      - type: bind
        source: ./src/resources
        target: /aidebate/resources # must be within our WORKDIR (i.e. 'aidebate')
