#{
#  will-be-replaced-from-environment: ${APP_NAME}
#  # `self` is a special variable that refers to this hierarchy.
#  reference-to-author-greeting: $self.author.greeting
#  author:
#    greeting: "Hello World!"
#  hobbies:
#    - creating
#    - hiking
#    # `me` is a special variable that refers to the current path within this hierarchy.
#    # In this case, `me` refers to `author.hobbies`
#    - "${self.me[0]} software"  # creating software
#}
langchain:
  project: "aidebate"
  endpoint: "https://api.smith.langchain.com"
dialogue:
  description: |
    Here is the topic of conversation: ${APP_DIALOGUE_TOPIC}.
    The participants are: ${APP_DIALOGUE_PERSONAS}.
  topic:
    prompt:
      system: "You can make a topic more specific."
      human: |
        ${APP_DIALOGUE_TOPIC}
        
        You are the moderator.
        Please make the topic more specific.
        Please reply with the specified quest in ${APP_DIALOGUE_WORD_LIMIT} words or less.
        Speak directly to the participants: (${APP_DIALOGUE_PERSONAS}).
        Do not add anything else.
  agent:
    chat_model:
      provider: openai # [openai|ollama] etc
      model: gpt-4 # [gpt-4|gpt-3.5-turbo|llama3|llama2] etc
      temperature: 0.2
    tool:
      # currently supported tools: [arxiv, ddg-search, wikipedia]
      names:
        - arxiv
        - ddg-search
        - wikipedia
      args:
        # set top_k_results=2 as part of the tool kwargs of the dialogue
        # agent to prevent results from overflowing the context limit
        top_k_results: 2
    prompt:
      system: |
        ${self.dialogue.description}
        
        Your name is %%persona%%.
        
        Your description is as follows: %%persona_description%%
        
        Your goal is to persuade your conversation partner of your point of view.
        
        DO look up information with your tool to refute your partner's claims.
        DO cite your sources.
        
        DO NOT fabricate fake citations.
        DO NOT cite any source that you did not look up.
        
        Do not add anything else.
        
        Stop speaking the moment you finish speaking from your perspective.
    description:
      prompt:
        system: "You can add detail to the description of the conversation participant."
        human: |
          ${self.dialogue.description}
          Please reply with a creative description of %%persona%%, 
          in ${APP_DIALOGUE_WORD_LIMIT} words or less. 
          Speak directly to %%persona%%.
          Give them a point of view.
          Do not add anything else.