define:
  &log_level 'INFO'
version: 1
formatters:
  simple:
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: *log_level
    formatter: simple
    filters:
      - secrets_masking_filter
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: *log_level
    formatter: simple
    filters:
      - secrets_masking_filter
    filename: resources/output/logs/aidebate.log
    maxBytes: 409600
    backupCount: 9
loggers:
  app:
    level: *log_level
    handlers: [console, file]
    propagate: false
root:
  level: *log_level
  handlers: [console, file]
filters:
  secrets_masking_filter:
    (): app.logging.SecretsMaskingFilter
    patterns:
      - "(pass|key|secret|token|jwt|hash|signature|credential|auth|certificate|connection|pat)"
